name: commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write # to publish to npm
      contents: write # to publish a GitHub release
      id-token: write # to use OIDC for npm provenance
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.1
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: pnpm
          registry-url: https://npm.pkg.github.com
          scope: "@joaofnds"
      - name: setup git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - run: pnpm install
      - run: pnpm run check
      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm exec lerna version --yes
      - run: pnpm exec lerna publish from-package --yes
