name: commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write # to publish to npm
      contents: write # to publish a GitHub release
      id-token: write # to use OIDC for npm provenance
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: "@joaofnds"
      - name: setup git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - run: npm ci
      - run: npm run check
      - run: npm run build
      - run: npm run test
      - run: npm run version
      - run: npm run publish
